name: Lint

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  php-lint:
    runs-on: ubuntu-latest
    name: PHP Syntax Check
    
    steps:
      - uses: actions/checkout@v5
      
      - name: PHP Syntax Check
        run: find . -name "*.php" -exec php -l {} \; || true
